version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: "3.11"
    commands:
      - export PATH=$HOME/.local/bin:$PATH
      - |
        [ -n "$(which poetry)" ] || \
        (curl -sSL https://install.python-poetry.org | python3 -)
  pre_build:
    on-failure: ABORT
    commands:
      - poetry install
  build:
    on-failure: ABORT
    commands:
      - export DB_PASSWORD="$(echo $DB_PASSWORD_JSON | jq -r '.password')" && poetry run alembic upgrade head

cache:
  paths:
    - /root/.local/**/*
    - /root/.cache/pip/**/*
