version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: "20"
    commands:
      - export PATH=$HOME/.local/bin:$PATH
      - mkdir -p $HOME/.cache/downloads
      - |
        [ -n "$(which terraform)" ] || \
        (([ -e $HOME/.cache/downloads/terraform.zip ] || curl -sSL https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip -o $HOME/.cache/downloads/terraform.zip) && unzip $HOME/.cache/downloads/terraform.zip -d $HOME/.local/bin)
      - |
        ([ -e $HOME/.cache/downloads/google-chrome-stable_current_x86_64.rpm ] || curl https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm -o $HOME/.cache/downloads/google-chrome-stable_current_x86_64.rpm) && yum install -y $HOME/.cache/downloads/google-chrome-stable_current_x86_64.rpm
      - |
        [ -n "$(which gauge)" ] || \
        (([ -e $HOME/.cache/downloads/gauge.zip ] || curl -sSL https://github.com/getgauge/gauge/releases/download/v1.6.8/gauge-1.6.8-linux.x86_64.zip -o $HOME/.cache/downloads/gauge.zip) && unzip $HOME/.cache/downloads/gauge.zip -d $HOME/.local/bin)
  pre_build:
    on-failure: ABORT
    commands:
      - |
        cd ${CODEBUILD_SRC_DIR}/terraform && echo -e "terraform {\n  backend \"s3\" {}\n}" > _override.tf && \
        terraform init \
          -backend-config="bucket=${S3_BUCKET_TFSTATE}" \
          -backend-config="key=${S3_KEY_TFSTATE}" \
          -backend-config="region=${AWS_REGION}"
      - cd ${CODEBUILD_SRC_DIR}/gauge && npm install --no-progress && gauge install && gauge config check_updates false
      - cd ${CODEBUILD_SRC_DIR}/gauge && npm install --no-progress
  build:
    on-failure: ABORT
    commands:
      - cd ${CODEBUILD_SRC_DIR} && bash scripts/deploy.sh
      - cd ${CODEBUILD_SRC_DIR} && bash scripts/test.sh
  post_build:
    on-failure: ABORT
    commands:
      - echo "Post test"

reports:
  gauge-tests:
    files:
      - gauge/reports/xml-report/result.xml
    file-format: JUNITXML

cache:
  paths:
    - /root/.cache/downloads/**/*
    - terraform/.terraform/**/*
